### ISSUE TITLE
print some VDM value are strange

### ISSUE THREAD

**Issue by shinsahara** [overturetool/overture#579] opened 2016-07-11 08:24 UTC
"print()" in IO.vdmpp is not enough?

Following VDM++ source print strange values for some VDM escape sequence values.

    class Test

    operations
    static public t1 : () ==> ()
    t1() == (
		IO`print("\",strange double quote,\t,\\,\x07,\',\u0007,\n");
		IO`println("\",strange double quote,\t,\\,\x07,\',\u0007")
    )
		
    end Test

And output is following:

    **
    ** Overture Console
    **
    \",strange double quote,	,\\,\a,',\a,
    \",strange double quote,	,\\,\a,',\a

    Test`t1() = ()

I think that output should be followings:

    ",strange double quote,	,\,a,',a,
    ",strange double quote,	,\,a,',a

Now, I found that the VDMTools's output are same strange values :-)
Is it my misunderstanding?

[print_VDM_value_is_strange.zip](https://github.com/overturetool/overture/files/356671/print_VDM_value_is_strange.zip)

**Comment by nickbattle** [comment] 2016-07-11 09:18
if you change the print and println to printf, then the IO library (at least in VDMJ) acts as you would expect. So this does point to a problem with print and println, in my view.

The problem is because the toString() of the VDM string passed re-creates the backslash quoting that is needed for the value. So for example, print "\"" produces "\"" - internally, the seq of char has a single quote character, but the toString of that sequence value re-quotes the character and puts the whole thing in double-quotes.

The printf function is different, so IO`printf("\"", []) will just produce a single quote on stdout. This is because printf uses an internal method to get the "real" string value of the first argument, rather than the toString value. Unfortunately, print and println do not do this, and I think they probably should to be consistent. It's a simple fix.

**Comment by nickbattle** [comment] 2016-07-11 09:35
Now fixed in ncb/development. I noticed that the Java codegen library also has an IO.java, but that the problem is already fixed there :-)

**Closed** 2016-07-22 22:47 UTC
Labels: bug, Mergable
