### ISSUE TITLE
Inherited definitions not visible in the launch configuration view

### ISSUE THREAD

**Issue by peterwvj** [overturetool/overture#431] opened 2015-03-11 15:11 UTC
If you try to set up a launch configurations in a PP model the inherited operations/functions are not show as possible entry points. For an example, consider the small model below:

~~~
class S

operations

public opS : () ==> ()
opS () == skip;	

end S

class C is subclass of S

operations

public opC : () ==> ()
opC () == skip;	

end C
~~~

Here class `C` has two (public) operations, namely `opC()` and `opS()` the latter being inherited from class `S`. Therefore `opS()` should appear as a possible entry point for the model. However, in the launch configuration view only `opC()` is shown - see image below.

![inherited](https://cloud.githubusercontent.com/assets/5388919/6599286/3bdb4280-c809-11e4-93d0-317194cea8ea.png)

**Comment by peterwvj** [comment] 2015-03-11 15:15
So a class stores its own definitions and its inherited definitions in separate lists. So probably what goes wrong is that only those definitions enclosed by the class are being considered. So in order to get hold of all the definitions probably something as shown below needs to be done:

~~~
List<PDefinition> allDefs = new LinkedList<PDefinition>(vdmClass.getDefinitions());
allDefs.addAll(vdmClass.getInheritedDefinitions());
~~~

**Comment by ldcouto** [comment] 2015-03-11 18:37
I know where to fix this. Remind tomorrow at the office and we'll knock it down.

**Comment by ldcouto** [comment] 2015-03-13 11:08
So, this is actually trickier than I thought.

If you have depth of inheritance > 1, a class will inherit multiple "versions" of the same def (one for each superclass above it ).

So, in the example below:
```
class A
instance variables
operations
public run: () ==> int
run() == return 1; 
end A
class B is subclass of A end B
class C is subclass of B end C
```

`C` will have 2 inherited definitions of `run` (and there is no easy way to distinguish between them). I'm not entirely sure if the tree should really be like this but that's not really the point. Showing multiple entries for the exact same definition is not a good idea. We need to make some design decisions here. I am inclined to just not allow inherited definitions to be entry points. If the user really wants to do it, it's easy to just add the operation to the subclass and call the relevant super.

There's also the issue of filtering out overridden definitions but that's more straightforward.

**Comment by nickbattle** [comment] 2015-03-13 12:18
​The problem is that operations in C can call run() (which is really
C`run()) or B`run() or A`run(). So you can explicitly refer to an inherited
(overridden) operation higher in the tree. It's a bit like super.run() in
Java, but allowing you to name the one you want.

So you *should* find that the three version of run() have different
"module" names? It would be a bit strange​ for someone to want to launch
class C by calling (say) B`run(), but it is legal, I think.

**Comment by ldcouto** [comment] 2015-03-13 13:41
Yeah, I figured that was the rationale. Although, in the case where `B` doesn't override `run`, you wonder how much sense it makes to actually inherit the two...

Both inherited definitions have `A` is their class definitions. As far as I can tell, the only way to distinguish is with `getName().getModule()` like you said. I suppose we could list each entry point as `operation name, class name, relevant superclass name` but I'm not sure what the syntax should be.

**Comment by nickbattle** [comment] 2015-03-13 14:13
​It's not that two are inherited as such, it's that the *same* operation
(in A) can be called as C`run(), B`run() or A`run(). ​So VDMJ represents
this as three separate named definitions (all pointing to the same
implementation, of course).

​I'm not clear whether you're saying that getName().getModule() returns A,
B and C or not?​

​I would say that the launcher should just be offered the "C" names (some
of which are inherited definitions).​

**Comment by ldcouto** [comment] 2015-03-13 14:38
Alright, let me try to clarify.

if `def` is an inherited definition in `C` in the aforementioned hierarchy...
`def.getModule()` returns `C` always
`def.getClassDefinition` returns `A`  everytime
`def.getSuperdef().getName().getModule()` returns `A` or `B` accordingly.

What I think the launch config search tree should offer is something like:
* `C`
 * ```A`run()```
 * ```B`run()```

This will let the user know which inherited definition is the entry point which may actually be relevant if their implementations differ.

Things get a bit trickier in the launch application selection dialog since that one doesn't have a tree and just presents the options as [operation name] - [class name] so it will be harder to represent each specific superclass.

Now, I want to say again that I'm not sure this is such a great idea. This will greatly expand the number of possible entry points and might just serve to make the user more confused. Are we sure we want this? @peterwvj , what do you think?

**Comment by peterwvj** [comment] 2015-03-13 18:20
It's actually not much of a problem since the launch configuration still allows you to execute `new C().opS()` in my original example as long as you specify the class/operation manually in the launch configuration dialog.

If we decide to proceed with this, one possibility could be to only show inherited definitions that allows the "super" call to go up one level. Rarely would you need to skip more levels in the hierarchy (although you can). Maybe showing everything is too confusing.So in your example, the launch configuration dialog could only offer `B`run()` for class `C`?

Thinking about it...I don't like that you can do "super.super" in VDM++ but that's a completely different story/RM :)

A related discussion about "super.super" for those who are interested: http://stackoverflow.com/questions/586363/why-is-super-super-method-not-allowed-in-java

**Comment by ldcouto** [comment] 2015-03-24 16:27
So, after some time I'm about ready to call this a "feature, not a bug". Showing all inherited definitions just makes the launchers a complete mess. Barring any objections I'll close this issue for the next release.

**Comment by peterwvj** [comment] 2015-03-24 16:37
I'm okay with that. Leaving it as it is a reasonable decision!

**Closed** 2015-03-30 06:09 UTC
Labels: bug
