### ISSUE TITLE
Functions in state variables crash variables view

### ISSUE THREAD

**Issue by ldcouto** [overturetool/overture#563] opened 2016-05-25 11:59 UTC
If you debug a model with lambdas in the state, when you set a breakpoint, the instance variables view is empty.

![untitled](https://cloud.githubusercontent.com/assets/582801/15539093/4e982b70-2278-11e6-9361-48c201ae346b.png)

Minimal example (commenting foo in and out shows it clearly):
```
class Foo
instance variables
foo : int -> int := lambda x:int &x;
bar :int :=0;

operations
public foobar : () ==> ()
foobar () == skip;
end Foo
```

I guess we have no printer for functions and that crashes the view. It's very silent though, I get no errors in the log.

**Comment by peterwvj** [comment] 2016-05-25 13:20
Thanks for the good bug report I think you're right. Here's a clue:

~~~
org.overture.ide.debug.core.dbgp.exceptions.DbgpDebuggingEngineException: 998: An internal exception in the debugger occurred
Detailed Message: org.overture.interpreter.values.UpdatableValue cannot be cast to org.overture.interpreter.values.FunctionValue
	at org.overture.ide.debug.core.dbgp.internal.utils.DbgpXmlParser.checkError(DbgpXmlParser.java:150)
	at org.overture.ide.debug.core.dbgp.internal.commands.DbgpDebuggingEngineCommunicator.communicate(DbgpDebuggingEngineCommunicator.java:117)
	at org.overture.ide.debug.core.dbgp.DbgpBaseCommands.communicate(DbgpBaseCommands.java:61)
	at org.overture.ide.debug.core.dbgp.internal.commands.DbgpContextCommands.getContextProperties(DbgpContextCommands.java:119)
	at org.overture.ide.debug.core.dbgp.internal.commands.DbgpCoreCommands.getContextProperties(DbgpCoreCommands.java:245)
	at org.overture.ide.debug.core.model.internal.VdmStackFrame.readVariables(VdmStackFrame.java:73)
	at org.overture.ide.debug.core.model.internal.VdmStackFrame.readAllVariables(VdmStackFrame.java:143)
	at org.overture.ide.debug.core.model.internal.VdmStackFrame.checkVariablesAvailable(VdmStackFrame.java:446)
	at org.overture.ide.debug.core.model.internal.VdmStackFrame.getVariables(VdmStackFrame.java:517)
	at org.eclipse.debug.internal.ui.model.elements.StackFrameContentProvider.getAllChildren(StackFrameContentProvider.java:53)
	at org.eclipse.debug.internal.ui.model.elements.StackFrameContentProvider.getChildCount(StackFrameContentProvider.java:29)
	at org.eclipse.debug.internal.ui.model.elements.ElementContentProvider.retrieveChildCount(ElementContentProvider.java:118)
	at org.eclipse.debug.internal.ui.model.elements.ElementContentProvider$2.run(ElementContentProvider.java:67)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
~~~

**Comment by ldcouto** [comment] 2016-05-25 13:24
Do you get that in the release? 

I think we need to fix this soon. I expect all the INTO-CPS people will need to use this feature. We can just print the function signature in the line: `f:A->B` or something

**Comment by peterwvj** [comment] 2016-05-25 13:29
I launched it in tethered mode. I'm looking more into it now.

**Comment by peterwvj** [comment] 2016-05-25 13:32
This seems to be caused by a obvious mistake in the code. I can now get it to show it. This looks fine, right?
![lambda-debug](https://cloud.githubusercontent.com/assets/5388919/15541666/d84c8194-228d-11e6-8e7e-a8691e85eb9f.png)

**Comment by peterwvj** [comment] 2016-05-25 13:48
It should be fixed now.

**Comment by ldcouto** [comment] 2016-05-25 13:51
Great job, guy! You can even see the lambda body.

**Comment by peterwvj** [comment] 2016-05-25 13:54
It's a `FunctionValue`  so you can get it printed nicely using the toString method :)

**Closed** 2016-05-28 10:09 UTC
Labels: bug, Mergable
