### ISSUE TITLE
Problem with type checking of rational numbers

### ISSUE THREAD

**Issue by peterwvj** [overturetool/overture#474] opened 2015-10-10 18:19 UTC
For the spec below the type checker reports three errors saying that it expects `rat` but finds `real`. Clearly `1.5` is a rational number so the spec should type check without any errors. VDMJ, on the other hand, does not produce any type errors, which is correct.

~~~
f :  () -> rat
f () == 1.5; -- Error reported

q :  () -> rat
q () ==
let a : rat = 1.5  -- Error reported  
in
  a;

values

v : rat = 1.5;  -- Error reported
~~~

Interestingly Overture type checks the operation below without producing any errors, which is correct.

~~~
operations

noErrors : () ==> rat
noErrors () ==
(
  dcl r : rat := 1.5;
  return r;
);
~~~

**Comment by nickbattle** [comment] 2015-11-18 13:25
This appears to have been a typo or VDMJ transposition error in the type check of real literals. If the value is not a whole number, VDMJ says the literal is a rat, but Overture was saying it was a real.

The second case works because the type of "r" is explicitly stated as rat, therefore although a "real" is being assigned, the type of the return value is "rat" rather than "real".

I'm just re-running the test suite.

**Comment by nickbattle** [comment] 2015-11-18 13:29
Hmm. This is causing one of the code generator tests to fail, though perhaps this is as expected. Can you have a look, PJ?

The fix is on line 2329 of TypeCheckerExpVisitor.java. The method should call newARationalNumericBasicType rather than newARealNumericBasicType.

**Comment by nickbattle** [comment] 2015-11-18 13:54
Actually, it looks like the reason for the dcl working is more subtle. It should fail because there is a definite type mismatch. But it is not doing so because there is no context being passed when the dcl assignments are checked. I'll look into that.

**Comment by nickbattle** [comment] 2015-11-18 14:01
OK, that was the problem. I'll attach a patch and perhaps you could commit the pair of fixes when the tests look OK?

[git.patch.txt](https://github.com/overturetool/overture/files/37893/git.patch.txt)

**Comment by peterwvj** [comment] 2015-11-18 16:24
Thanks, Nick. I'll let you know when I know what the problem is with the code generator!

**Comment by nickbattle** [comment] 2015-11-18 16:26
I don't think it's a problem as such, it's just that this changes the output, but you're better placed to check what's generated than I am.

**Comment by peterwvj** [comment] 2015-11-18 19:15
I tried to apply the patch but I get a lot of problems with unresolved types. Many of the type checker test fail on my machine. The issue (or at least one of them) can be demonstrated using the small example below:
~~~
class A

operations

public op : () ==> nat
op () == 
(
	dcl a : A := new A();
	
	return 0;
)

end A
~~~

Which gives me the following type errors when I try to code generate it:

~~~
Found errors in VDM model:Type check errors:
Error 3428: Unknown type: (unresolved A`A) in 'A' ... at line 8:13
~~~

Do you also have this problem or did I somehow I get a wrong patch? My patch changes `TypeCheckerStmVisitor.java` and `TypeCheckerExpVisitor.java`

**Comment by nickbattle** [comment] 2015-11-18 19:47
Hmm, sorry. Try taking just the expression visitor change. That should fix the rat/real problem. Then I can look at the other part separately.

**Comment by peterwvj** [comment] 2015-11-18 20:19
Thanks, that got rid of the unresolved type errors. Still of the some SCSK type checker tests seem to cause problems (only 3 tests though)

As an example, consider the snippet from `cgip/sltest/SL/state/state-02.vdm`:

~~~
state Sigma of
  v1  : bool
  v2  : nat1
  v3  : nat
  v4  : int
  v5  : rat
...
  init s == s = mk_Sigma(true, -- bool
                         10, -- nat1
                         0, -- nat
                         -1,  --int
                         3.3, -- rat
~~~~
The test fails because the type checker for some reason reports the error shown below (which it should not).
~~~
Error 3327: state-02.vdm at 67:26 Value is not of the right type
~~~

**Comment by peterwvj** [comment] 2015-11-18 20:49
Applying the expression visitor change revealed a small issue with handling of rational numbers in the code generator. I pushed it to pvj/main and it's safe to merge.

**Comment by nickbattle** [comment] 2015-11-19 08:55
OK, thanks. I'll merge with pvj/main and then investigate why the "dcl" fix causes other issues.

**Comment by nickbattle** [comment] 2015-11-19 09:50
Hmm. So I merged with pvj/main (d251c12), which doesn't seem to have the rat/real code fix(?), and that passes all the tests. Applying the real to rat fix, a JML test is failing, differently to before but it looks entirely reasonable:

Failed tests:
  JmlOutputTests.run:47->checkGenJavaJml:118 Stored Java/JML is different from generared Java/JML expected:<.../@ assert Utils.is_r[eal](realPattern_1);
  ...> but was:<.../@ assert Utils.is_r[at](realPattern_1);
  ...>

So can I go ahead and tweak that expected result too (where is it?).

**Comment by nickbattle** [comment] 2015-11-19 10:18
So fixing this (a small change to one JML file), with the real->rat fix, the entire test suite now runs cleanly for me. I committed 765d12e with the real/rat code change and the JML test fix and pushed to ncb/development.

So can you clarify the remaining problems above? (I could try it, but I'm supposed to be working :-))

**Comment by peterwvj** [comment] 2015-11-19 12:23
Sorry, I forgot to run the JML generator tests. Thanks for updating the test artefacts.

In addition to the `state-02.vdm` test error (see comment above) there are two more tests that fail (three in total). See summary below:

~~~
Failed tests: 
  ExternalsDemoTest>ParamFineGrainTest.testCase:102->compareResults:47->compareResults:71 Error in test state-02.vdm : 
Expected (but not found) Strings: 
Error 3327: state-02.vdm at 67:26 Value is not of the right type
Found (but not expected) Strings: 
state-02.vdmparses and type checks

  ExternalsDemoTest>ParamFineGrainTest.testCase:102->compareResults:47->compareResults:71 Error in test recmodify-05.vdm : 
Expected (but not found) Strings: 
Error 3327: recmodify-05.vdm at 14:27 Value is not of the right type
Found (but not expected) Strings: 
recmodify-05.vdmparses and type checks

  ExternalsDemoTest>ParamFineGrainTest.testCase:102->compareResults:47->compareResults:71 Error in test recmodify-12.vdm : 
Expected (but not found) Strings: 
Error 3327: recmodify-12.vdm at 14:27 Value is not of the right type
Found (but not expected) Strings: 
recmodify-12.vdmparses and type checks
~~~

The problem with the `recmodify-05.vdm` test is in fact similar to that of `state-02.vdm` (see comment above).

~~~
Error 3327: recmodify-05.vdm at 14:27 Value is not of the right type
...
    cases f(10):
      0 -> 10,
      5 -> mk_ReC("Hello",8.6), --line 14
...
ReC:: j: seq of char
      i : rat;
....
~~~
The last test failure is (test `recmodify-12.vdm`) the exact same issue with as with `recmodify-05.vdm`.

So I guess that the three tests `state-02.vdm`, `recmodify-05.vdm` and `recmodify-12.vdm` all fail for the same reason, i.e. the type checker will not allow you to instantiate records with fields that are declared to be of type `rat`.

This should clarify the remaining problems. Does this help?

**Comment by nickbattle** [comment] 2015-11-19 12:56
Hmm. Well, there was definitely one extra problem that affected "dcl" statements. I've pushed commit 3003e9b which should fix this - all the tests now run for me, including two which now detect extra errors that they previously missed.

But I haven't seen any that are concerned with state or recmodify, so I'm still a bit confused by that. Can you merge with ncb/development and see what that gives you?

**Comment by nickbattle** [comment] 2015-11-19 13:00
Incidentally, the error was another one of these horrible problems where the state in the "question" is being passed around between various visitors and needs to temporarily take on different values. There are probably more of these lurking. It only really happens with the visitor pattern - with a simple recursive call with parameters, you get the behaviour for free. Another part of the problem is that ASTv2 has multiple copies of (in this case) PTypes, and whereas VDMJ can resolve a type once and effectively set all of the copies, Overture has to separately resolve each one.

**Comment by peterwvj** [comment] 2015-11-19 13:47
When I merge (fast-forward) ncb/development one of the type checker tests starts to fail because the type checker correctly(!) reports an error for a `dcl` statement:
~~~
Tests run: 1216, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 7.505 sec <<< FAILURE!
test[blockstmt.vdm](org.overture.typechecker.tests.external.ExternalModulesSlTypeCheckTest)  Time elapsed: 0.02 sec  <<< FAILURE!
java.lang.AssertionError: Errors found in file "blockstmt.vdm.result"

Unexpected Error:   3327 blockstmt.vdm at 42:35 Value is not of the right type

  BlockStmt5: () ==> nat * nat
  BlockStmt5() ==
    (dcl b : bool := let n = 9 in n; -- line 42
     if b
     then return mk_(6,8)
~~~
This test is also included as part of the `core/testing` external tests. In addition, I still have the three external tests that fail. I test using the following command:

~~~
mvn test -Dmaven.test.skip=false -Dmaven.javadoc.skip=true -DexternalTestsPath=/home/peter/dev/tests/ -q -Dmaven.test.redirectTestOutputToFile=true
~~~

If you adopt this command to use your local path for the SCSK test and run it in `ovtrepo/core/testing` do you then see these test errors?

Finally, your type checker tweaks also also made the type checker report an error for one of the JML generator test input files (a correct type error). I updated the test input file on my branch so you can get it if you merge pvj/main.

**Comment by nickbattle** [comment] 2015-11-19 13:52
But I thought we agreed (from a previous bug fix!) that the external tests were now co-located inside the Overture tree as a Git submodule thing? So I don't have any external test folder now. I just run the tests with:

$MVN -gs c:/Users/battlenc/.m2/Overture_Settings.xml -Dmaven.javadoc.skip=true $@ test

I'm assuming that includes the external tests because they're in "externals/docrepo". So perhaps the version of the submodule thing that I have doesn't match the external copy that you're using??

**Comment by peterwvj** [comment] 2015-11-19 13:57
I think we got you confused - sorry about that. The submodule is only for the standard examples that ship with the tool (e.b. AlarmPP). This has nothing to do with the SCSK examples.

The SCSK examples are still stored in the AU gitlab repository.

**Comment by nickbattle** [comment] 2015-11-19 16:16
Ah right, the "externals" folder is for the tests that are external and the externalTestsPath points to the tests called "externalTests" that are actually SCSK tests. Meanwhile, the (internal) testing project has "extests" folder that has results files for the external tests (not sure which), and "tests" which also has results for some external tests (not sure which, but it looks the same as the other one to me). I *think* the results for the external (as in submodule) tests are in the "externals" folder rather than being in a separate tests folder.

Then, of course, when there is an error in one of these tests, the test output tells you that it concerns a file called (say) "spec.vdm". There isn't much clue to where that may be, and a casual search for the filename is often able to return a dozen or more files with the same name scattered throughout the tree.

And don't get me started on how you work out what -D flag setting to use to reset test results, or the fact that there isn't always one.

I know this isn't your fault PJ (or anyone's in particular), but **no one outside Core will ever be able to work with this mess**. Unpicking VDMJ bugs in an AST2 visitor system is trivial compared to trying to unpick the tests that fail afterwards.

So... I think that the few external tests that now fail all fail for the right reasons. Some are missing errors that should never have been there, and some are new errors that should always have been there. If you can figure out how to tweak the external results to match, you're doing a lot better than me :-(

**Comment by nickbattle** [comment] 2015-11-19 16:17
I'll mark this as mergable as it's basically OK, I think.

**Comment by peterwvj** [comment] 2015-11-19 17:25
I merged `ncb/development` and updated the result files. Based on the changes to the result files, your fixes seem to be okay. If you merge (fast-forward) `pvj/main` you should get the new result files too.

I updated the type checker test by passing the following property `-Dtests.tc.override.all` to the type checker. The `core/testing` result files I updated by passing `-Dtests.update.example.ExternalsDemo
`. I always look for the name of the test that fail and from there I'm able to find the property to pass by browsing the related Java files.

I agree this is confusing. It's not okay that you have to search Java sources to find out what property you need to pass in order to update the result files. If a test fail it should probably tell you what property you need to use to update the affected result files.

I'll try to set up an issue so we can find a better and simpler way to test the tool.

**Closed** 2015-11-19 17:25 UTC
Labels: bug, Mergable
