### ISSUE TITLE
scope of inherited constant values

### ISSUE THREAD

**Issue by tomooda** [overturetool/overture#407] opened 2015-01-24 12:54 UTC
The scope of inherited constant values looks strange in function bodies and constant definitions.
With the following VDM++ spec,

```
class A
    values
        public a = 1;
end A
class B is subclass of A
    values
        --public b1 = a;
        public b2 = A`a;
    functions
        public f1 : int -> int
        f1(i) == i * a;
        public f2 : int -> int
        f2(i) == i * A`a;
end B
```

p new B().f1(1) results in an error message: Error 4034: Name 'B`a' not in scope in 'B'.
p new B().f2(1) works fine.
VDMJ on a command shell can evaluate the both without an error.

"values public b1 = a;" in class B causes an error on both Overture and VDMJ.

The constant a is visible in operation bodies and initializers of instance variables as expected.

**Comment by nickbattle** [comment] 2015-01-24 20:36
The problem seems to be that, when the static variables for the class are being initialized (and "values" are statics), the local inherited definition of B`a (inherited from A`a) is not recognised as a value definition and is not being included in the static environment.

This happens in the setStaticValues of SClassDefinitionAssistantInterpreter. The isValueDefinition method of the PDefinitionAssistant is returning false. In VDMJ, the LocalDefinition for A`a is marked as a "value definition" for this purpose. It seems this is missing or not correctly implemented in Overture.

**Comment by nickbattle** [comment] 2015-01-24 20:41
The DefinitionValueChecker used for this was missing a specialized method for ALocalDefinitions. Adding this, and returning the value of the "valueDefinition" flag, fixes the problem, as far as I can tell. I'll run some more tests.

**Comment by nickbattle** [comment] 2015-01-24 21:21
Now fixed in ncb/development. The problem would only affect the use of inherited value definitions, which is perhaps why we've not seen this before.

**Comment by nickbattle** [comment] 2015-01-26 10:38
> "values public b1 = a;" in class B causes an error on both Overture and VDMJ.

This was caused by a problem in the initialization of a class, where inherited values (B`a) in this case were created after things that might use them. The fix swaps the order, so the inherited environment is fully available before the local values are created, which makes more sense.

**Closed** 2015-02-09 10:18 UTC
Labels: bug, Mergable
