### ISSUE TITLE
Operation declared pure is reported as impure when it is applied in VDM-SL

### ISSUE THREAD

**Issue by pglvdm** [overturetool/overture#501] opened 2016-02-01 09:46 UTC
With a VDM-SL definition such as
~~~
state System of
  accounts : map AccountId to Account
  illegalCards : set of CardId
  curCard : map TillId to [Card]
  cardOk : map TillId to bool
  retainedCards : map TillId to set of Card
inv mk_System(accs,-,curCard,cardOk,-) == 
      dom curCard subset dom cardOk and
      (forall tid in set dom curCard &
         curCard(tid) = nil => not cardOk(tid)) and 
      (forall id1, id2 in set dom accs &
        id1 <> id2 =>
        dom accs(id1).cards inter dom accs(id2).cards = {})
init s == s = mk_System({|->},{},{mk_token("t1") |-> nil},
                        {mk_token("t1") |-> false},{|->})
end

types
  Account :: cards : map CardId to Cardholder
             balance : nat
             transactions : seq of Transaction
  inv account == TransactionsInvariant(account.transactions);

  Transaction :: date : Date
                 cardId : CardId
                 amount : nat;

  Card :: code : Code
          cardId : CardId
          accountId : AccountId;

  Cardholder :: name : Name;

  AccountId = nat;
  Name = seq of char;
  CardId = nat;
  Code = nat;
  PinCode = nat;
  Date = seq of char;
  TillId = token;

functions

  TransactionsInvariant : seq of Transaction +> bool
  TransactionsInvariant(ts) ==
    forall date in set {ts(i).date | i in set inds ts} &
      DateTotal(date,ts) <= dailyLimit;

  DateTotal : Date * seq of Transaction +> nat
  DateTotal(date,ts) ==
    Sum([ts(i).amount | i in set inds ts & ts(i).date = date]);

values
  dailyLimit : nat = 2000;

operations

  InsertCard : TillId * Card ==> ()
  InsertCard(tid,c) ==
    curCard(tid) := c
  pre tid in set dom curCard and curCard(tid) = nil;

  Validate : TillId * PinCode ==> <PinOk> | <PinNotOk> | <Retained>        
  Validate(tid,pin) ==
    let codeOk = curCard(tid).code = Encode(pin),
        cardLegal = IsLegalCard(curCard(tid)) 
    in
      (if not cardLegal then 
        (retainedCards(tid) := retainedCards(tid) union {curCard(tid)};
         cardOk(tid) := false;
         curCard(tid) := nil;
         return <Retained>)
       else
         cardOk(tid) := codeOk;
       return if cardOk(tid)
              then <PinOk>
              else <PinNotOk>)
  pre tid in set dom curCard and
      curCard(tid) <> nil and not cardOk(tid);

  ReturnCard : TillId ==> ()
  ReturnCard(tid) ==
    (cardOk(tid)  := false;
     curCard(tid) := nil)
  pre tid in set dom curCard and curCard(tid) <> nil;

  GetBalance : TillId ==> nat
  GetBalance(tid) ==
    return accounts(curCard(tid).accountId).balance
  pre tid in set dom curCard and
      curCard(tid) <> nil and cardOk(tid) and IsLegalCard(curCard(tid));

  MakeWithdrawal : TillId * nat * Date ==> bool
  MakeWithdrawal(tid,amount,date) ==
    let mk_Card(-,cardId,accountId) = curCard(tid),
        transaction = mk_Transaction(date,cardId,amount)        
    in
      if accounts(accountId).balance - amount >= 0 and 
        DateTotal(date,accounts(accountId).transactions^[transaction])
        <= dailyLimit
      then
        (accounts(accountId).balance := 
           accounts(accountId).balance - amount;
         accounts(accountId).transactions := 
           accounts(accountId).transactions ^ [transaction];
         return true)
     else 
       return false
  pre tid in set dom curCard and
      curCard(tid) <> nil and cardOk(tid) and IsLegalCard(curCard(tid));

  RequestStatement : TillId ==> Name * seq of Transaction * nat
  RequestStatement(tid) ==
    let mk_Card(-,cardId,accountId) = curCard(tid),
        mk_Account(cards,balance,transactions) = accounts(accountId)
    in
      return mk_(cards(cardId).name,transactions,balance)
  pre tid in set dom curCard and
      curCard(tid) <> nil and cardOk(tid) and IsLegalCard(curCard(tid));

  pure IsLegalCard : Card ==> bool
  IsLegalCard(mk_Card(-,cardId,accountId)) ==
    return cardId not in set illegalCards and 
           accountId in set dom accounts and
           cardId in set dom accounts(accountId).cards;

  ReportIllegalCard : CardId ==> ()
  ReportIllegalCard(cardId) ==
    illegalCards := illegalCards union {cardId};

  AddAccount : AccountId * Account ==> ()
  AddAccount(accountId,account) ==
    accounts := accounts munion {accountId |-> account}
  pre accountId not in set dom accounts;

functions
  Encode: PinCode +> Code
  Encode(pin) ==
    pin; -- NB The actual encoding procedure has not yet been chosen

  Sum: seq of real +> real
  Sum(rs) ==
    if rs = [] then 0
    else
      hd rs + Sum(tl rs)
  measure Len;

  Len: seq of real +> nat
  Len(list) ==
    len list;
~~~
`IsLegalCard` is used three times where that falty bug report is provided.

**Comment by ldcouto** [comment] 2016-02-01 09:59
Here is a much smaller example of the same problem.

```
operations
pure foo :() ==> bool
foo() == is not yet specified;

bar1 : () ==> ()
bar1() == skip
pre foo();
```

**Comment by nickbattle** [comment] 2016-02-01 10:02
This is a duplicate of #499. Applying that fix corrects the specification above. I'll close this as duplicate.

**Closed by nickbattle** 2016-02-01 10:02 UTC
Labels: bug, duplicate
