### ISSUE TITLE
Overture 2.6.0 displays error-occurred dialog

### ISSUE THREAD

**Issue by Phiroc** [overturetool/overture#663] opened 2018-01-28 14:23 UTC
### Description

When you double-click Overture 2.6.0, a dialog appears stating that an error occurred and that you should refer to the log in the /Users/<name>/<path to Overture workspace>/.metadata/.log directory. 

### Steps to Reproduce

1. Install Overture 64-bit Mac say, in /Applications/Overture Directory

2. Specify the workspace's path; e.g. /Users/<user>/Documents/Overture/workspace2

3. Double-click the application

**Expected behavior:** 

Overture runs

**Actual behavior:** 

A dialog appears stating that an error occurred and that you should refer to the log in the /Users/<name>/<path to Overture workspace>/.metadata/.log directory. 
Yet, the .metadata directory is empty.

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

2.6.0 64-bit Mac on MacOSX 10.12.6 (Sierra)

java version "9.0.1"
Java(TM) SE Runtime Environment (build 9.0.1+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode)

**Comment by peterwvj** [comment] 2018-01-29 07:23
Thanks for reporting.

Could you try to follow the instructions listed in the [FAQ](http://overturetool.org/faq/) and let me know if that works.

I see you're testing the release candidate - thanks (2.6.0 isn't out yet)! This issue might be caused by the release candidate not being signed. I forgot to mention that in the email when I sent out the release candidate. Can you confirm that Overture 2.5.4, downloaded from http://overturetool.org/download/ , works on your machine?

Once Overture 2.6.0 is released, it *will* be signed.

**Comment by peterwvj** [comment] 2018-01-29 07:34
If the suggestion above doesn't fix your issue then try the suggestion below.

I see you're using Java 9.

Overture builds against Eclipse (Oxygen). Unfortunately, there's a bug in Eclipse that causes it to crash on all Java 9 builds. You'll find the corresponding bug report [here](https://bugs.eclipse.org/bugs/show_bug.cgi?id=493761). Assuming that your issue is Java 9 related: does any of the workarounds suggested there work?

**Comment by Phiroc** [comment] 2018-01-29 22:25
Hi Peter,
unfortunately, neither version 2.5.4 and 2.5.6 seem to work with Java 9, whether downloaded with wget or with a browser. I’ve also tried adding the following line to the Overture.ini file within Overture.app, but to no avail:

-vm
/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/home/bin

Best regards,
Philippe

**Comment by peterwvj** [comment] 2018-01-30 07:26
I still think that the problem is related to the Java9 bug in Eclipse. Recently, there was a MAC (Sierra) user who had a similar problem. He was also using Java9. He fixed the issue by changing his Overture.ini within Overture.app to:

-startup
../Eclipse/plugins/org.eclipse.equinox.launcher_1.4.0.v20161219-1356.jar
--launcher.library
../Eclipse/plugins/org.eclipse.equinox.launcher.cocoa.macosx.x86_64_1.1.550.v20170928-1359
-vmargs
--add-modules=java.se.ee
-Dosgi.requiredJavaVersion=1.8
-XstartOnFirstThread
-Dorg.eclipse.swt.internal.carbon.smallFonts
-Xms256m
-Xmx1024m

I'm not sure you need everythng listed there. To begin with you could try to add the vmargs. Also the `org.eclipse.equinox.launcher_1.4.0.v20161219-1356.jar` and `org.eclipse.equinox.launcher.cocoa.macosx.x86_64_1.1.550.v20170928-1359` files may have slightly different names on your machine, I'm not sure.

Does that work?

**Comment by DragosDumitrache** [comment] 2018-02-02 09:53
@peterwvj I've tried your suggestion above but didn't work. What did work was adding the following VM flag to the Overture.ini file. 
```
-vm
/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/bin/java
```
Your actual jdk version may differ, but that seems to fix it

**Comment by peterwvj** [comment] 2018-02-02 10:33
That's excellent - thanks for letting us know about your fix This confirms that the issue was related to the Java 9 bug in Eclipse. I'll consider this issue closed for now.

**Comment by Phiroc** [comment] 2018-02-02 10:36
Hi,

I'll test it tonight on my machine.

Regards,

Philippe

----- Mail original -----
De: "Peter W. V. Tran-Jørgensen" <notifications@github.com>
À: "overturetool/overture" <overture@noreply.github.com>
Cc: "Phiroc" <phiroc@free.fr>, "Author" <author@noreply.github.com>
Envoyé: Vendredi 2 Février 2018 11:33:22
Objet: Re: [overturetool/overture] Overture 2.6.0 displays error-occurred dialog (#663)



That's excellent - thanks for letting us know about your fix This confirms that the issue was related to the Java 9 bug in Eclipse. I'll consider this issue closed for now.

**Comment by peterwvj** [comment] 2018-02-02 11:13
Sorry for closing the issue, I simply forgot that @Phiroc 's issue had not been solved yet. I'll re-open the issue for now. Let us know when you have tested it on your machine - thanks.

**Comment by Phiroc** [comment] 2018-02-02 19:16
Hello,

Here’s the contents of my Overture.ini file:

-startup
../Eclipse/plugins/org.eclipse.equinox.launcher_1.3.201.v20161025-1711.jar
--launcher.library
../Eclipse/plugins/org.eclipse.equinox.launcher.cocoa.macosx.x86_64_1.1.401.v20161122-1740
-vmargs
-Xmx512m
-Dosgi.requiredJavaVersion=1.8
-XstartOnFirstThread
-Dorg.eclipse.swt.internal.carbon.smallFonts
-vm
/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/bin/java


When I run "open -a Overture" in the /Applications/Overture directory (where the Overture.app is located) the Select Directory dialog appears. I then type the following in the input field: 

/Users/philippe/Documents/Overture/wk1

and press OK. Next, the "An error has occurred" dialog appears, containing the following text:

« See the log file /Users/philippe/Documents/Overture/wk1/.metadata/.log ».

Here’s the log file’s contents:

!SESSION 2018-02-02 20:03:25.653 -----------------------------------------------
eclipse.buildId=unknown
java.version=9.0.1
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=fr_FR
Framework arguments:  -keyring /Users/philippe/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -keyring /Users/philippe/.eclipse_keyring

!ENTRY org.eclipse.osgi 4 0 2018-02-02 20:03:41.061
!MESSAGE Application error
!STACK 1
org.eclipse.e4.core.di.InjectionException: java.lang.NoClassDefFoundError: javax/annotation/PostConstruct
        at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:386)
        at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:294)
        at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:162)
        at org.eclipse.e4.ui.internal.workbench.swt.E4Application.createDefaultHeadlessContext(E4Application.java:490)
        at org.eclipse.e4.ui.internal.workbench.swt.E4Application.createDefaultContext(E4Application.java:504)
        at org.eclipse.e4.ui.internal.workbench.swt.E4Application.createE4Workbench(E4Application.java:203)
        at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:632)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
        at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:610)
        at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
        at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)



Best regards,

Philippe

**Comment by DragosDumitrache** [comment] 2018-02-02 19:20
@Phiroc Apologies, I should have mentioned, specify the -vm before the vmargs. That should fix it. Are you also using the jdk 1.8.0_144? You should be able to navigate to it easily then. Otherwise, update with the right version as necessary.

**Comment by Phiroc** [comment] 2018-02-02 21:47
Hi Dragos,

Yes, jdk 1.8.0_144 is installed on my machine:

jdk-9.0.1.jdk		jdk1.8.0.jdk		jdk1.8.0_144.jdk
jdk1.7.0_51.jdk		jdk1.8.0_121.jdk	jdk1.8.0_60.jdk

putting vm before vmargs fixed the issue. 

Many thanks.

Best regards,

Philippe

**Comment by peterwvj** [comment] 2018-02-03 15:25
Very good, guys. I'll close the issue.

**Closed by peterwvj** 2018-02-03 15:25 UTC

**Comment by peterwvj** [comment] 2018-03-20 11:59
Another option worth trying, if you want to run Overture (or just regular Eclipse) on a Java 9 VM is to add the following line to your Overture.ini file:

```
--add-modules=ALL-SYSTEM
```
Source: https://wiki.eclipse.org/Configure_Eclipse_for_Java_9#Configure_Eclipse_for_Java_9_modules
