### ISSUE TITLE
static constructor that is new’ed

### ISSUE THREAD

**Issue by jaesparza** [overturetool/overture#449] opened 2015-05-29 08:18 UTC
Execution results:

**
** Overture Console
**

New class will be created.null
Initialization: java.lang.NullPointerException
java.lang.NullPointerException
	at org.overture.interpreter.debug.DBGPReader.quote(DBGPReader.java:834)
	at org.overture.interpreter.debug.DBGPReader.errorResponse(DBGPReader.java:708)
	at org.overture.interpreter.debug.DBGPReaderV2.process(DBGPReaderV2.java:720)
	at org.overture.interpreter.debug.DBGPReader.run(DBGPReader.java:844)
	at org.overture.interpreter.debug.DBGPReader.connect(DBGPReader.java:553)
	at org.overture.interpreter.debug.DBGPReader.startup(DBGPReader.java:561)
	at org.overture.interpreter.debug.DBGPReaderV2.main(DBGPReaderV2.java:533)

__________

class TheClass

instance variables

  private stateCounter : nat := 0;
  
  private static theInstance : seq of TheClass:= [];
  inv len theInstance < 2; -- Be one instance or nil
  
operations

private static TheClass : () ==> TheClass
TheClass() == skip;

public static getTheClass : () ==> TheClass
getTheClass() == (
if (len theInstance = 1) then (
	  IO`print("\nThe class already exists.");
	  return hd theInstance; )
	else (
		IO`print("\nNew class will be created."); 
	  theInstance := [TheClass`TheClass()];
	  return hd theInstance;
	);
);

end TheClass
_________

used as follows from main:

class main

instance variables
   private myState : TheClass;
   
operations

public entryPoint: () ==> ()
entryPoint() == 
(
  myState := TheClass`getTheClass();
);

end main;

**Comment by ldcouto** [comment] 2015-05-29 08:31
This is an interesting issue. I'm not sure if VDM++ supports static constructors. The language manual is not specific either way so I guess that implies static constructor are ok...

Jose, for your use case, is it essential that the constructor be static? If you just need the singleton pattern, switching to a "normal" constructor should work:
```
private TheClass : () ==> TheClass
TheClass() == skip;

public static getTheClass : () ==> TheClass
getTheClass() == (
if (len theInstance = 1) then (
IO`print("\nThe class already exists."); return hd theInstance; ) else ( IO`print("\nNew class will be created."); 
theInstance := [new TheClass()];
return hd theInstance;
);
)
```

**Comment by jaesparza** [comment] 2015-05-29 09:40
Hi Luis,

Yes indeed, a "normal" constructor as you are suggesting will work fine. The thing is that in the beginning I used this static constructor (by mistake) and resulted in that null pointer party.

Kenneth suggested that I reported it as an issue in github since (as far as I understood) the static keyword could not be in there. I think this is more of a language issue and unfortunately out of my expertise.

Cu!

**Comment by ldcouto** [comment] 2015-05-29 12:09
Ok, that makes sense. Thanks for reporting it.

I guess Kenneth is suggesting that static constructors are not allowed.
Hopefully someone from the language board can weigh in so we can be certain.

**Comment by nickbattle** [comment] 2015-06-01 17:48
Not sure I'm speaking for the Language Board here, but a few observations.:

VDMTools specifically prohibits static constructors, so Overture should do the same - so this is a bug in the type checker (and simple to fix).

Looking more closely at the failing specification above, the get operation is doing something unusual, by calling the constructor operation directly as an operation (TheClass'TheClass()) rather than using the "new" operator. This is a known error/feature in VDMTools and Overture, though I can't find an open bug report for it(?). The new aspect of the problem here is that with a static constructor, calling it as an operation causes a null pointer exception, whereas calling a non-static constructor as an operation works (in VDMTools as well).

**Comment by nlmave** [comment] 2015-06-01 20:09
All,

I suggest the following:
(a - short term) harmonize the behavior with VDMTools; implement the bug 
fix as suggested by Nick
(b) raise an issue (request for clarification) with the LB to (1) 
discuss this and (2) fix the LRM to describe this better (at the least)

If the issue is raised this week, we can pick it up on the upcoming LB 
meeting on Sunday

My two cents worth,
Marcel

**Comment by ldcouto** [comment] 2015-06-02 08:43
Sounds good. I've opened the issue here: https://github.com/overturetool/language/issues/32

@nickbattle calling constructors without the `new` keyword seems a bit bizarre.I assume that should not be allowed either?

**Comment by peterwvj** [comment] 2015-06-02 10:04
Calling constructors without using the `new` keyword is how super classes get initialized so we can't (completely) disallow it. Other than that I agree with you.

**Comment by nickbattle** [comment] 2015-06-02 11:42
​Ah yes, very good point! We would have to distinguish between calls to a
constructor from within another constructor (allowed, if it's one of your
parents' constructors) and calls from elsewhere (disallowed).

**Comment by ldcouto** [comment] 2015-06-02 11:48
Right, so to sum-up, here is the bugfix:

* [ ] report error when declaring a constructor as static
* [ ] report error when calling a constructor without the `new` expression from outside a subclass

I think both of these should be handled by the type checker. Agreed?

**Comment by nickbattle** [comment] 2015-06-02 12:35
​Yes, these are both missing type checks. The first one is easy. The second
one requires a lot of context and will be a bit trickier.​

**Comment by ldcouto** [comment] 2015-06-02 13:25
Does it? Isn't it enough to go up the tree and look for a constructor?

**Comment by nickbattle** [comment] 2015-06-02 16:17
The problem is working out that you are in a constructor and then making that fact available further down the "walk" of the type check. I haven't looked into it yet, but it may not be that difficult - just a bit trickier than checking for a static keyword!

**Comment by nickbattle** [comment] 2015-06-04 15:58
With some tweaks, VDMJ is now saying the following for the original spec:
```
Parsed 1 class in 0.164 secs. No syntax errors
Error 3286: Constructor cannot be 'async' or 'static' in 'TheClass' (test.vpp) at line 12:16
Error 9999: Cannot call a constructor from here in 'TheClass' (test.vpp) at line 19:17
Type checked 1 class in 0.012 secs. Found 4 type errors
Bye
```
I'll do some more tests and give that 9999 a proper number, but I think this will give us what we need. Then I'll apply it to Overture.

**Comment by nickbattle** [comment] 2015-06-05 12:11
Now fixed in ncb/development.

**Comment by ldcouto** [comment] 2015-06-05 14:03
Excellent job Nick :)

**Closed** 2015-06-09 18:27 UTC
Labels: bug, Mergable
