### ISSUE TITLE
Inconsistent import behaviour

### ISSUE THREAD

**Issue by paulch42** [overturetool/overture#521] opened 2016-03-27 03:14 UTC
Consider the modules
```
module import1
exports all
definitions 
types
  A :: a:nat;
end import1
```
and
```
module import2
exports all
definitions 
types
  B :: b:nat;
end import2
```
If we now define the module
```
module import3
imports from import1 all
exports all
definitions 
functions
  f:import1`A -> import2`B
  f(-) == undefined;

  g:import1`A -> import2`B
  g(-) == mk_import2`B(1); -- ERROR: Unknown type 'import2`B in constructor' 
end import3
```
An error is reported in the definition of `g` which is expected since the module does not import `import2`. However, no error is reported in the definition of `f` even though it refers to type `B` from the `import2` module which is not imported. This suggests it is allowed to refer to types from a module that is not imported, but not allowed to create expressions of those types.

**Comment by nickbattle** [comment] 2016-03-28 20:57
I agree this is apparently inconsistent. The reason this happens is that in order to "resolve" all of the types in the specification (ie. link the names used to their type definitions), the type checker passes the complete type environment to each module (like a super "imports from all"). It can do this because it is trying to understand what a given named type refers to independent of whether there is an import that puts it within scope. Subsequent type checking then determines whether each type "usage" (ie. not in a type clause of a definition, but in the body of an expression) is within scope and type compatible etc. So mk_import2'B(1) is raised as an error because the type is not in scope, but the use of import2'B in the type signature of f is not raised as an error, as it does refer to a valid type.

The problem is that, having resolved the types within function signature, the type checking does not subsequently check that the type referred to is within scope. This would be consistent! It looks like this should be simple to fix.

**Comment by peterwvj** [comment] 2016-05-05 23:23
Did you try to update the type checker to check that the types are within scope?

**Comment by nickbattle** [comment] 2016-07-07 10:26
Now fixed on ncb/development.

**Comment by nickbattle** [comment] 2016-07-15 11:12
We need to re-open this, unfortunately. The fix I applied does work for simple test cases, and evidently for all the test cases in the Maven suite, but when you have a very complicated set of inter-dependent modules, the absence of the "universal type list" prevents the type resolution from working.

I'll try to think of an alternative solution, but this problem isn't critical as it stands. The changes have been reverted and pushed to GitHub.

**Closed** 2016-07-22 22:47 UTC
Labels: bug
