### ISSUE TITLE
The interpreter fails to report a type invariant violation

### ISSUE THREAD

**Issue by peterwvj** [overturetool/overture#446] opened 2015-05-19 00:30 UTC
Given the spec below. If you execute `Run()` the interpreter fails to see that `x` represents an illegal value. Note that the type invariant for type `C` strictly requires values of this type to be the character value `'a'`. Still, executing `Run()` yields `'b'` and no errors are reported.

It's the same for Overture and VDMJ.
~~~
module Entry

exports all
definitions

types

C = char
inv c == c = 'a';
  
operations

Run : () ==> ?
Run () ==
let x : C = 'b' 
in 
  return x;

end Entry
~~~
You can do something similar with a type definition based on `bool`, i.e.
~~~
True = bool
inv b == b = true'
~~~

**Comment by peterwvj** [comment] 2015-05-19 00:33
If I do a similar model that uses `nat` instead of `char` the errors gets reported.

~~~
module Entry

exports all
definitions

types

C = nat
inv c == c = 2;
  
operations

Run : () ==> ?
Run () ==
let x : C = 1 
in 
  return x;

end Entry
~~~

**Comment by nickbattle** [comment] 2015-05-19 07:43
​OK, confirmed - it's the same in VDMJ too. Curious. I'll look at it.​

**Comment by nickbattle** [comment] 2015-05-19 08:24
This is happening for character, boolean and token types. The problem is in the type conversion system where a value is converted to a particular type (here, an invariant type). But the test is wrong. Instead of saying "is the type a simple character type (with no invariant)?" it is saying "is the type able to hold a character (possibly with an invariant)?". This leads it to create a simple CharacterValue instead of an InvariantValue, and so changes to the value subsequently are not checked against the invariant.

The fix is to correct the test for the three types concerned.

**Comment by nickbattle** [comment] 2015-05-19 11:04
Now fixed in ncb/development.

**Comment by peterwvj** [comment] 2015-05-19 11:18
Excellent Nick - thanks for the explanation too!

**Closed** 2015-06-09 18:27 UTC
Labels: bug, Mergable
