### ISSUE TITLE
Pure operation checks not working in SL

### ISSUE THREAD

**Issue by nickbattle** [overturetool/overture#499] opened 2016-01-31 13:36 UTC
It looks like there is a problem with the TC of pure operations in VDM-SL. The following simple pure operation gives no TC errors in Overture (2.3.0):
```
state S of
	x : nat
end

operations
	pure op: () ==> ()
	op() ==
		x := 123;
```
But in VDMJ it complains as expected:
```
Parsed 1 module in 0.155 secs. No syntax errors
Error 3338: Cannot update state in a pure operation in 'DEFAULT' (TestSL.vdmsl) at line 9:9
Error 3344: Pure operation 'op' must return a value in 'DEFAULT' (TestSL.vdmsl) at line 6:10
Type checked 1 module in 0.008 secs. Found 2 type errors
```

**Comment by nickbattle** [comment] 2016-01-31 14:02
Not sure how we missed this one! But it's now fixed in ncb/development.

**Comment by peterwvj** [comment] 2016-01-31 14:19
Cool. I guess we've been too focused on testing PP and RT. Is this a duplicate of #498 ?

**Comment by nickbattle** [comment] 2016-01-31 14:28
There wouldn't have been a null pointer exception, and I think Peter's bug is in the UI code not the parser/TC. So no, I think #498 is different.

Yes, presumably all the focus on pure operation testing was in PP/RT.

**Comment by ldcouto** [comment] 2016-01-31 19:15
If it's a different bug, can someone update the description?

Did you test it with this fix, Nick?

**Comment by ldcouto** [comment] 2016-01-31 19:16
I can update the description, once it's confirmed that it's indeed UI

**Comment by ldcouto** [comment] 2016-01-31 20:48
I'm happy this is fixed but after thinking on it...

I wasn't even aware you could use pure ops in SL. Are we sure they're needed? Maybe across modules?

**Comment by nickbattle** [comment] 2016-02-01 09:21
I couldn't reproduce Peter's problem on Linux. The fix to this issue surely has nothing to do with it. It was a simply typo in the pure processing for SL (which reflects badly on our testing, but the effect is relatively contanined).

We did discuss whether pure oprations should be available in SL, and there is explicit code in there to support them (ie. it's not there by accident!). I agree it's less useful than for PP, but I'm happy to have the feature. It's meaning is the same in SL (except only a subset of the OO restrictions apply, of course).

**Comment by ldcouto** [comment] 2016-02-01 09:27
Per #498, we have figured out that it's a SWT/OSX issue. Not much we can do.

I certainly don't want to reopen the pure can of worms (heh!) but I will say that I never tested pure ops with SL models -- I was only thinking of OO then.

Regardless, we should add a few TC test cases to ensure that pure ops work in SL. We can just take the PP tests and convert them. Shall I open a new issue for this?

**Comment by nickbattle** [comment] 2016-02-01 09:30
Could we just use this one?

**Comment by ldcouto** [comment] 2016-02-01 10:16
This issue? Sure.

I'll update the tags.

I think we need the following checks:

- [ ] pure invoked in assertion -- no error
- [ ] impure invoked in assertion -- error 
- [ ] impure op invoked in pure op -- error
- [ ] pure op invoked in pure op -- no error
- [ ] pure op invoked in function -- referential transparency warning (still applies?)
- [ ] pure op body does no assignments -- no error
- [ ] pure op body does assignments -- error

**Comment by ldcouto** [comment] 2016-02-01 10:21
So here is one example of correct pure op invocation in assertions from #501
```
operations
pure foo :() ==> bool
foo() == is not yet specified;

bar1 : () ==> ()
bar1() == skip
pre foo();
```

**Comment by ldcouto** [comment] 2016-02-11 17:21
I don't think is fixed yet.

I wrote the test sources suggested above. At least 2 things are incorrect:
* pure ops invoked in functions yields an error
* assignments in pure ops yield no error

You can check this out in ldc/puresltests. I've committed the test sources and will look into the errors later.

**Comment by nickbattle** [comment] 2016-02-11 21:38
Are you sure? This is working for me in ncb/development. Did you merge with me?
```
state S of
    x : nat
end

operations
    pure op: () ==> nat
    op() ==
    (
    	x := 0;		-- Error 3338: Cannot update state in a pure operation
        return 123
    )

functions
	f: () -> nat
	f() == op();	-- Warning 5017: Pure operation call may not be referentially transparent
```
If you comment out that assignment, then f() returns 123.

**Comment by peterwvj** [comment] 2016-02-11 22:55
It seems to work for me to on `pvj/main`

~~~
peter@peter-ubuntu:~/dev/ovtrepo/core/commandline/target$ cat -n SlDemo.vdmsl
     1	state S of
     2	    x : nat
     3	end
     4	
     5	operations
     6	    pure op: () ==> nat
     7	    op() ==
     8	    (
     9	        x := 0;     -- Error 3338: Cannot update state in a pure operation
    10	        return 123
    11	    )
    12	
    13	functions
    14	    f: () -> nat
    15	    f() == op();    -- Warning 5017: Pure operation call may not be referentially transparent
peter@peter-ubuntu:~/dev/ovtrepo/core/commandline/target$ java -jar Overture-2.3.1-SNAPSHOT.jar -vdmsl -i SlDemo.vdmsl 
Parsed 1 module in 0.084 secs. No syntax errors
Error 3338: Cannot update state in a pure operation in 'DEFAULT' (SlDemo.vdmsl) at line 9:9
Warning 5017: Pure operation call may not be referentially transparent in 'DEFAULT' (SlDemo.vdmsl) at line 15:12
Type checked 1 module in 0.068 secs. Found 1 type error and 1 warning
Bye
~~~

**Comment by ldcouto** [comment] 2016-02-12 07:35
Very strange. I branched off development. I thought all fixes had been
merged in. Anyway, I reran after merging with pvj and the results are
correct so I've merged the tests into development.

**Closed** 2016-02-12 07:35 UTC
Labels: enhancement
