### ISSUE TITLE
"Improve" auto-completion

### ISSUE THREAD

**Issue by ldcouto** [overturetool/overture#423] opened 2015-03-03 12:07 UTC
*Edited by @peterwvj*

The current version of the auto-completion feature now includes:

- Several fixes for the existing auto completion feature
- Use of (dynamic) templates to improve auto completion for invocation of explicit functions and operations for the *enclosing* class (similar to how auto completion works in Eclipse/Java)
- Proposals are now sorted alphabetically
- Proposals now also include basic types, functions and operations
- Blended list of proposals: Different kinds of proposals are shown in the same context menu
- Auto completion of record constructors (`mk_`)
- Auto completion of class constructors (`new`)
- Auto completion of token constructors (`mk_token`)

There is already set up a test to exercise the auto-completion feature - see:

https://github.com/overturetool/overture/blob/pvj/main/ide/ui.tests/src/main/java/org/overture/ide/ui/CompletionContextTest.java#L16-L69

**Comment by peterwvj** [comment] 2016-01-15 13:57
@pglvdm What's the status on this? Do we still have these students working on it?

**Comment by pglvdm** [comment] 2016-01-15 13:58
yes we have 2 students doing an R&D project on this during the next semester.

**Comment by ldcouto** [comment] 2016-01-15 14:34
Are they on GithHub? Can we get them to report what they're up to?

**Comment by pglvdm** [comment] 2016-01-15 14:45
Peter Mathiesen <pkmathiesen@gmail.com> og Magnus Louvmand Pedersen <louvmand@gmail.com> and I assume that they are on GitHub. I don't that they are very far yet because they are having exams at the moment I am sure we can get them reporting when the group meetings start again in February

**Comment by peterwvj** [comment] 2016-03-28 16:37
#522 includes Peter's and Magnus' work on the auto completion feature. Below is a summary of their work:

- Several fixes for the existing auto completion feature
- Use of (dynamic) templates to improve auto completion for invocation of explicit functions (similar to how auto completion works in Eclipse/Java)
- Proposals are now sorted alphabetically
- Proposals now also include basic types, functions and operations
- Blended list of proposals: Different kinds of proposals are shown in the same context menu
- Auto completion support for the `mk_` constructor

We still need to test their work before we merge it into `development`

**Comment by peterwvj** [comment] 2016-03-28 17:53
I tried to play around with the auto completion feature. Some initial thoughts/input:

Peter's and Magnus' work seems to work quite well. There are, however, problems with auto completion for some of the other VDM constructs. For example, I noticed that completion proposals for constructors sometimes did not work (see figure below)

![ctor-autocomplete-bug](https://cloud.githubusercontent.com/assets/5388919/14085005/bf6d3cec-f51d-11e5-82a5-c312ecb5731c.png)

I very much like the new auto completion feature for explicit that uses dynamic templates. It would be useful if auto completion for `mk_` and constructors (i.e. `new`) worked in a similar way.

**Comment by petemachine** [comment] 2016-03-29 10:43
We wrote a report about our contributions to the Overture IDE.
The report is available on the SVN for download:

https://svn.nfit.au.dk/svn/iha_pgl-MasterThesis/MagnusPeter/R&D%20-%20Auto-completion%20in%20Overture/R&D%20-%20Auto-completion%20in%20Overture%20-%20Magnus%20&%20Peter%20-%20Report.pdf

**Comment by peterwvj** [comment] 2016-03-29 11:08
To avoid struggling with authorization I just uploaded it to Github.

[R&D - Auto-completion in Overture - Magnus & Peter - Report.pdf](https://github.com/overturetool/overture/files/193301/R.D.-.Auto-completion.in.Overture.-.Magnus.Peter.-.Report.pdf)

**Comment by peterwvj** [comment] 2016-03-29 14:21
Magnus and Peter already made more auto-completion improvements, which include

* Support for implicit and explicit functions and operations
* Completion of the `mk_` record constructor is updated to use dynamic templates

**Comment by petemachine** [comment] 2016-04-02 14:28
There is now a corrected and updated version of the report available based on the feedback from PGL.

[R&D - Auto-completion in Overture - Magnus & Peter - Report.pdf](https://github.com/overturetool/overture/files/200867/R.D.-.Auto-completion.in.Overture.-.Magnus.Peter.-.Report.pdf)

Furthermore the slides from our presentation are now available, which gives an overview of the work carried out in the project.

[R&D - Auto-completion in Overture - Magnus & Peter - Slideshow.pdf](https://github.com/overturetool/overture/files/200869/R.D.-.Auto-completion.in.Overture.-.Magnus.Peter.-.Slideshow.pdf)

**Comment by peterwvj** [comment] 2016-04-02 14:30
Great! Thanks for uploading this.

**Comment by peterwvj** [comment] 2016-04-05 09:49
@petemachine I tried to play around with the `mk_` auto-completion support

In the body of the operation in the spec below I typed `mk_` and Ctrl+SPACE and chose `R(x,y)` from the list of proposals. I was expecting it to complete to `mk_R(x,y)` but instead it removed the `mk_` keyword.

~~~

types

R :: x : int y : int;

operations

op : () ==> ()
op () == 
let r = R(x, y);  -- should be completed as mk_R(x,y)
~~~

**Comment by peterwvj** [comment] 2016-04-05 09:58
In addition we have the problem with completion of `new` as described above.

**Comment by petemachine** [comment] 2016-04-05 10:24
We improved the `new` completion, but some small bugs are still present.
The `mk_` bug is new to us, but we can try to look into that.

**Comment by petemachine** [comment] 2016-04-05 11:25
@peterwvj we can't seem to reproduce the `mk_` bug you mentioned, so we will try to make a pull request, so you can try with the most recent code.
One of the main bugs in `new` is now also fixed, but we still need it to show the default contstructors. We will try to make this in a near future, so it can be tested and maybe merged into development.

**Comment by peterwvj** [comment] 2016-04-05 11:40
Sounds very good, guys!

**Comment by petemachine** [comment] 2016-04-05 15:40
Default constructors are now added. We will try to make a pull request tomorrow.

**Comment by peterwvj** [comment] 2016-05-03 13:13
The record constructors seem to work now. However, I can't get class constructor proposals to work when I type `new` and then Ctrl+SPACE. Does it work on your machine? Nothing shows up on mine.

In addition, found a small problem with the way operations are presented

![constructors](https://cloud.githubusercontent.com/assets/5388919/14984090/45297fbe-1141-11e6-94b2-8922ffc41f62.png)

When I auto-complete the operation (which is really a constructor) it shows X(--), whereas it should show X(-,-), right?

**Comment by petemachine** [comment] 2016-05-10 19:07
Last I checked, there were no problems with `new`, but it has been some weeks since we last worked on the tool.
I think you are right about the operation/constructor example, and we can try to look at the different problems when we are done with the semester.

**Comment by peterwvj** [comment] 2016-05-10 19:35
Thanks!

**Comment by peterwvj** [comment] 2016-07-10 10:06
@petemachine Did you find time to look at the issues raised in my previous comment? That is, (1) the problem with class constructors and (2) presentation of operations?

**Comment by petemachine** [comment] 2016-07-11 18:34
@peterwvj No, not yet. will see if i can find some spare time to look at it, but i'm on summer holiday at the moment.

**Comment by petemachine** [comment] 2016-07-12 10:48
@peterwvj `new` works on my machine, but I have not pulled the last 63 commits yet. Will keep you updated.

**Comment by peterwvj** [comment] 2016-07-12 10:55
Very good, thanks!

**Comment by petemachine** [comment] 2016-07-12 10:57
I don't think that we are currently differentiating constructors from other explicit operations, but I will try to look into the issue with the operation completion with (-,-) in it.

**Comment by peterwvj** [comment] 2016-07-12 11:01
It might that this is just a problem with operations, as you suggest

**Comment by petemachine** [comment] 2016-07-12 11:20
In the specific example you posted, wouldn't you expect it to show X(nat,nat) in the proposal?

**Comment by peterwvj** [comment] 2016-07-12 11:24
You normally use the convention `X(<parameter-name>, <parameter-name>)`, right? Therefore I think that `X(-,-)` is expected.

**Comment by petemachine** [comment] 2016-07-12 11:32
I don't recall, but you might be right. I found the problem with the missing comma now. It seems to be a problem when we use the hyphen, since two hyphens have the same id, and we check on this id when inserting the comma. I will try to fix it.

**Comment by peterwvj** [comment] 2016-07-12 11:38
Sounds good! Thanks

**Comment by petemachine** [comment] 2016-07-12 13:01
I made it write `X(-,-)` in the proposal, but the completion of it doesn't work. Not sure if the template generations is messed up by the hyphens or what seems to be the problem, but i might not be able to fix this right away and i leave on a weeks vacation tomorrow. I will ask Magnus to take a look at it.

**Comment by peterwvj** [comment] 2016-07-12 13:25
Okay that's fine. If Magnus could report the progress here then that would be great. Btw. have a nice vacation :)

**Comment by petemachine** [comment] 2016-07-12 13:35
Yes, i will tell him to if he has the time to look at it. Thank you :)

**Comment by petemachine** [comment] 2016-08-22 14:12
@peterwvj We looked into the issue with X(-,-) and the problem is that special characters in the template generation is not allowed, so we have to figure out how to escape the special characters. We will try to fix it during this week.

**Comment by louvmand** [comment] 2016-08-24 06:47
I have been looking at the template core of eclipse and it is  not possible to use special characters.  There is also a problem when the two parameters have the same name because the when you write in one of them, the other one is mirrored.  So i suggest that we create a template like X(parameter1, parameter2)  is that  acceptable?

**Comment by peterwvj** [comment] 2016-08-24 08:24
Hi @petemachine and @louvmand . Use of special characters is only a problem for the "don't care" pattern ("_"), right? That's the only *special* character I can think of that can appear in a name. I would assume that it is possible to assign unique names to "don't care" patterns that appear in the same parameter list.  I think it's fine if you replace them with something such as "ignore<number>" or what you suggest.

When you "correct" the parameter names that contain special characters, I think you need to make sure that the new names do not collide with parameters names already used. I had a similar issue another place in the code. To addresss this, you could collect names that have already been used (names `toAvoid`) and use that to construct a new name that has not already been used:

```Java
public String getName(String suggestion)
{
  if (!toAvoid.contains(suggestion))
  {
    toAvoid.add(suggestion);
    return suggestion;
  } else
  {
    int counter = 1;

    String prefix = suggestion + "_";

    String newSuggestion = prefix + counter;

    while (toAvoid.contains(newSuggestion))
    {
      counter++;
      newSuggestion = prefix + counter;
    }

    toAvoid.add(newSuggestion);
    return newSuggestion;
  }
}
```

Note that the code snippet above uses `_` as a delimiter, which might not work for your purposes. The snippet is taken from https://github.com/overturetool/overture/blob/development/core/codegen/vdm2jml/src/main/java/org/overture/codegen/vdm2jml/util/NameGen.java 

Does this help?

**Comment by peterwvj** [comment] 2016-08-24 08:25
Actually, there might also be other problems with characters such as ø, æ and å or japanese characters?

**Comment by louvmand** [comment] 2016-08-24 19:30
I will try to fix this tomorrow and I will definitely be looking at the getName() function it seems like a good solution

**Comment by peterwvj** [comment] 2016-08-24 19:35
Sounds good, thanks!

**Comment by peterwvj** [comment] 2016-08-27 10:32
Hi. After playing around with the #590 I found the following issues. First, auto-completion for empty prefixes are showing `ArrayIndexOutOfBoundsException` in the problem view. To produce this problem, create a model as shown below and type `Ctrl+SPACE`.

![propose-anything](https://cloud.githubusercontent.com/assets/5388919/18026670/1a0364a8-6c4f-11e6-9166-d7f886dc39f9.png)


```Java
java.lang.java.lang.ArrayIndexOutOfBoundsException: -1
	at org.overture.ide.ui.templates.VdmCompletionContext.regexStringCleaner(VdmCompletionContext.java:92)
	at org.overture.ide.ui.templates.VdmCompletionContext.init(VdmCompletionContext.java:67)
	at org.overture.ide.ui.templates.VdmCompletionContext.<init>(VdmCompletionContext.java:26)
	at org.overture.ide.ui.completion.CompletionUtil.computeVdmCompletionContext(CompletionUtil.java:81)
	at org.overture.ide.ui.templates.VdmContentAssistProcessor.computeCompletionProposals(VdmContentAssistProcessor.java:73)
	at org.eclipse.jface.text.contentassist.ContentAssistant$3.run(ContentAssistant.java:1931)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.jface.text.contentassist.ContentAssistant.computeCompletionProposals(ContentAssistant.java:1928)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup.computeProposals(CompletionProposalPopup.java:565)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup.access$16(CompletionProposalPopup.java:560)
....
```
A second, perhaps related problem, is that no proposals are listed if I type `new ` and then `Ctrl+SPACE` (see example below).

![new-no-completion](https://cloud.githubusercontent.com/assets/5388919/18026682/b246e2e4-6c4f-11e6-8d89-feba692dafe2.png)

Lastly, I noticed a problem related to operation proposals that can be demonstrated using the `AlarmPP` example that bundles with the tool. See the `Plant(,{map to x to y})` proposal in the figure below, which, I believe, originates from the constructor defined as `public Plant: set of Alarm * map Period to set of Expert`. I would imagine that this problem can also be produced if you combine other type constructors to form complex types.

![plan-ctor](https://cloud.githubusercontent.com/assets/5388919/18026717/b9b628e0-6c50-11e6-873e-23a13a5d7911.png)

**Comment by peterwvj** [comment] 2016-08-30 12:48
Below is some input based on #592.

First, I should say that this feature is starting to work quite well. However, I found a few issues:

First, I noticed that the default constructor (which always exists) is only listed in the proposals if there exist another user-specified constructor for a given class. This problem is shown in the figure below. I am suggesting (for consistency) that the `B()` constructor also be shown.

![default-ctor-missing](https://cloud.githubusercontent.com/assets/5388919/18089278/6714d3c2-6ebf-11e6-84f3-848130ee78ee.png)

Furthermore, it is possible to crash the proposals calculator by asking Overture to list proposals for `a.` as shown below.

![dot-proposals](https://cloud.githubusercontent.com/assets/5388919/18089325/b1249a6a-6ebf-11e6-87fd-22b1efbdc211.png)

The stacktrace is:

```Java
java.lang.ArrayIndexOutOfBoundsException: 1
	at org.overture.ide.ui.templates.VdmCompletionContext.consDotContext(VdmCompletionContext.java:102)
	at org.overture.ide.ui.templates.VdmCompletionContext.init(VdmCompletionContext.java:62)
	at org.overture.ide.ui.templates.VdmCompletionContext.<init>(VdmCompletionContext.java:26)
	at org.overture.ide.ui.completion.CompletionUtil.computeVdmCompletionContext(CompletionUtil.java:81)
	at org.overture.ide.ui.templates.VdmContentAssistProcessor.computeCompletionProposals(VdmContentAssistProcessor.java:73)
	at org.eclipse.jface.text.contentassist.ContentAssistant$3.run(ContentAssistant.java:1931)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at 
...
```

**Comment by peterwvj** [comment] 2016-09-27 07:44
The features seem to work faily well, so I'm closing this issue.

**Closed by peterwvj** 2016-09-27 07:44 UTC
Labels: enhancement
