### ISSUE TITLE
Assignment to local constants not rejected by the type checker

### ISSUE THREAD

**Issue by pglvdm** [overturetool/overture#448] opened 2015-05-20 18:24 UTC
For a model such as:
~~~
class Test

types

Rec :: b : bool
       r : nat
     
instance variables

s : set of Rec := {}

operations

public Op: () ==> ()
	-- Dispense specified amount of specific payload type from this group
Op() ==
  let e in set s
	in 
		if e.b
		then e.r := 9
		else e.r := 0; 
			
end Test
~~~
here assignment to something with e should really be rejected by the type checker.

**Comment by nickbattle** [comment] 2015-05-21 06:56
Confirmed in VDMJ. Looks like it's not checking for "state" in the assignment, only "name". I'll investigate.

**Comment by pglvdm** [comment] 2015-05-21 07:00
Great! I was VERY surprised when I saw one of my students doing this yesterday…

P
Peter Gorm Larsen
Professor, PhD (head of software engineering)
Telephone: +45 41 89 32 60
Mail: pgl@eng.au.dk
Aarhus University, Department of Engineering, Finlandsgade 22, DK-8200 Aarhus N, Phone: +45 41893000

**Comment by nickbattle** [comment] 2015-05-21 07:06
This is interesting. VDMJ is assuming that, since e is one of the members of the state set s, that it is referring to a piece of updatable state and acn therefore be assigned to. But I suppose this is "object reference" thinking: the value e is not a piece of state once it has been selected like this. It is just a value. So it sounds like "let" definitions need to be de-stated.

**Comment by nickbattle** [comment] 2015-05-21 13:08
OK, VDMJ is now saying the following for your example. I need to do some more testing, but it's looking OK.
```
Parsed 1 class in 0.206 secs. No syntax errors
Error 3301: Variable 'e' in scope is not updatable in 'Test' (test.vpp) at line 20:14
Error 3301: Variable 'e' in scope is not updatable in 'Test' (test.vpp) at line 21:14
Type checked 1 class in 0.016 secs. Found 2 type errors
Bye
```

**Comment by nickbattle** [comment] 2015-05-21 15:54
OK, now fixed in ncb/development.

**Closed** 2015-06-09 18:27 UTC
Labels: bug, Mergable
