### ISSUE TITLE
Overture is unable to start the debugging engine.

### ISSUE THREAD

**Issue by ritchje** [overturetool/overture#639] opened 2017-08-30 13:46 UTC
I get the following console output when trying to start debugging:

```
Initialization: java.lang.NullPointerException
java.lang.NullPointerException
	at org.overture.interpreter.debug.DBGPReader.quote(DBGPReader.java:834)
	at org.overture.interpreter.debug.DBGPReader.errorResponse(DBGPReader.java:708)
	at org.overture.interpreter.debug.DBGPReaderV2.process(DBGPReaderV2.java:720)
	at org.overture.interpreter.debug.DBGPReader.run(DBGPReader.java:844)
	at org.overture.interpreter.debug.DBGPReader.connect(DBGPReader.java:553)
	at org.overture.interpreter.debug.DBGPReader.startup(DBGPReader.java:561)
	at org.overture.interpreter.debug.DBGPReaderV2.main(DBGPReaderV2.java:533)
```

I am presented with the following error message:

```
Launching testbench has encountered a problem.
errDebuggingEngineNotInitialized
```

This is the case for a simple specification such as:

```
module Main
definitions 
  
types

  A :: x : int y : int;

functions

  add: int * int -> int
  add(a, b) ==
    a + b; -- breakpoint here
  
end Main
```

Interestingly, if I remove the type definitions, it allows me to debug. Value definitions seem to be ok though.

My build/os info:

```
macOS: 10.12.6 (16G29)

Overture Platform
Version: 2.5.0
Build date: 2017 Aug 10 13:31 CEST
Git commit description: Release/2.5.0
```

**Comment by nickbattle** [comment] 2017-08-30 14:32
Hi Ritchie, and thanks for the detailed bug report. We've already fixed this problem, and it should be released in 2.5.1 shortly. You're absolutely right that the problem is caused by the type definition. It's also linked to searching for the source location of breakpoints.

If you need a fix for this urgently, there is a "test" snaphot build available.

**Comment by ritchje** [comment] 2017-08-30 14:41
Thanks for the heads up Nick. Where can I find the test snapshot build?

**Comment by nickbattle** [comment] 2017-08-30 14:48
The test builds are here: http://overture.au.dk/overture/test/. I think they are generally accessible. Take the latest. Let us know if it fixes your problem.

**Comment by shinsahara** [comment] 2017-09-01 08:29
Hi all,

I met same error too.
My model is not too simple. So, I can't avoid the problem to date.

This model is OK on Overture Tools 2.4.6.

My Environment are:

Mac OS Sierra version 10.12.6(16G29)

Overture Platform:
Version: 2.5.0
Build date: 2017 Aug 10 13:31 CEST
Git commit description: Release/2.5.0.

Cheers,
Shin
s

**Comment by nickbattle** [comment] 2017-09-01 08:31
Yes Shin, it's a problem in 2.5.0 with the new eq/ord processing. So you wouldn't get the issue in 2.4.6. The latest test build ought to fix it for you though.

**Closed** 2017-09-01 08:41 UTC
Labels: bug, Mergable
