### ISSUE TITLE
All tests fail in the CarNaviRadioRT example

### ISSUE THREAD

**Issue by bandurvp** [overturetool/overture#472] opened 2015-10-01 09:59 UTC
Hi all,

I am new to the group, so please bear with me.  All the tests generated by the TT trace in Test.vdmrt under the example project CarNaviRadioRT fail with the following:

``Error 4065:  Error 4011:  Illegal history operator:  #fin in 'EnvironmentTask' at line 85:21.''

Peter reliably informs me that this is in fact a bug.

**Comment by nickbattle** [comment] 2015-10-01 11:40
I've had a quick look at this. It seems to be produced by the following line:
```
per IsFinished => #fin(logSysToEnv) > 0;
```
The problem is that IsFinished is a static operation, therefore when the trace test calls EnvironmentTask`IsFinished(), it has a static class context (ie. it can see static operations, but not others or instance variables). So when it encounters #fin(logSysToEnv) in the predicate, which is a non-static method, it does not know which object instance to count the finish counter for.

I'm not sure what the correct solution is here. It looks like a missing type checking error to me? How did this ever work?

**Comment by nickbattle** [comment] 2015-10-01 11:44
Incidentally, the double error "Error 4065: Error 4011:" is because the context exception raised by the first error is caught and re-thrown in caseAHistoryExp of ExpressionEvaluator. It's harmless therefore, but it should just re-throw the error.

**Comment by nickbattle** [comment] 2015-10-01 11:57
The type check of the history expression searches through all of the operations defined in the class, since it has to account for overloads (caseAHistoryExp in TypeCheckerExpVisitor). If it was doing a normal Environment "findName", then it would fail to find logSysToEnv because the enviornment is marked as static (because IsFinished is static). So this is not raising a type check error, but this would be the place to do it, if we decide this is what it needs.

**Comment by nickbattle** [comment] 2015-10-01 12:30
There's something else strange going on. I tried the same test on VDMJ, which has the same bug with IsFinished. But (because of scheduler differences), VDMJ actually starts to execute the async operations (in most tests) before the IsFinished guard is checked.

Most of these operations are failing immediately because the envTasks map in World has not been established. This is because the CT test does not call either of the RunScenario operations in World which set up the envTasks.

So... interesting question about the missing static type check error, but I think this spec is nonsense.

**Comment by nickbattle** [comment] 2015-11-08 12:06
The patch attached works, but I'm still trying to figure out how to reset the expected test results from the example tests.
[git.patch.txt](https://github.com/overturetool/overture/files/29497/git.patch.txt)

**Comment by nickbattle** [comment] 2015-11-11 13:35
Now fixed in ncb/development.

**Closed** 2016-01-15 14:31 UTC
Labels: bug, Mergable

**Comment by pglvdm** [comment] 2016-02-19 15:51
ok this was an error in the example. I have just fixed it...

**Comment by peterwvj** [comment] 2016-02-19 16:18
If the fix to the model is suppose to ship with version 2.3.2 then the sub module in the Overture tool repository needs to be updated. This affects the release so Anders should be made aware of it.

**Comment by pglvdm** [comment] 2016-02-19 16:20
that is great. I also made a small fis of the Tree VDM++ example...

**Comment by peterwvj** [comment] 2016-02-19 17:15
According to the release process (see https://github.com/overturetool/overture/wiki/Release-Process) your changes on the `editing` should be pulled into the `master` branch anyway so it should not be a problem.

**Comment by bandurvp** [comment] 2016-02-22 12:27
Hi Peter,

I can't find this change in the repo.  Which branch did you make it on?

Victor
